#############################################################################
# Makefile for building: mycar
# Generated by qmake (3.1) (Qt 5.12.5)
# Project:  mycar.pro
# Template: app
# Command: /home/mateusz/raspi/qt5/bin/qmake -o Makefile mycar.pro -spec devices/linux-rasp-pi-g++ CONFIG+=qtquickcompiler
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /home/mateusz/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-gcc
CXX           = /home/mateusz/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s -march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard --sysroot=/home/mateusz/raspi/sysroot -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s -march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard --sysroot=/home/mateusz/raspi/sysroot -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/raspi/sysroot/usr/include/ -I../../../raspi/qt5pi/include -I../../../raspi/qt5pi/include/QtWidgets -I../../../raspi/qt5pi/include/QtGui -I../../../raspi/qt5pi/include/QtCore -I. -I../../../raspi/sysroot/opt/vc/include -I../../../raspi/sysroot/opt/vc/include/interface/vcos/pthreads -I../../../raspi/sysroot/opt/vc/include/interface/vmcs_host/linux -I. -I../../../raspi/qt5/mkspecs/devices/linux-rasp-pi-g++
QMAKE         = /home/mateusz/raspi/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/mateusz/raspi/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/mateusz/raspi/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = mycar1.0.0
DISTDIR = /home/mateusz/Desktop/QtPojects/mycar/.tmp/mycar1.0.0
LINK          = /home/mateusz/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++
LFLAGS        = -mfloat-abi=hard --sysroot=/home/mateusz/raspi/sysroot -Wl,-O1 -Wl,-rpath,/usr/local/qt5pi/lib -Wl,-rpath-link,/home/mateusz/raspi/sysroot/opt/vc/lib -Wl,-rpath-link,/home/mateusz/raspi/sysroot/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link,/home/mateusz/raspi/sysroot/lib/arm-linux-gnueabihf
LIBS          = $(SUBLIBS) -L/home/mateusz/raspi/sysroot/opt/vc/lib -lrt -lpigpiod_if2 /home/mateusz/raspi/qt5pi/lib/libQt5Widgets.so /home/mateusz/raspi/qt5pi/lib/libQt5Gui.so /home/mateusz/raspi/qt5pi/lib/libQt5Core.so /home/mateusz/raspi/sysroot/usr/lib/arm-linux-gnueabihf/libGLESv2.so -lpthread   
AR            = /home/mateusz/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = /home/mateusz/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = DriveModule.cpp \
		SensorsModule.cpp \
		main.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = DriveModule.o \
		SensorsModule.o \
		main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = ../../../raspi/qt5/mkspecs/features/spec_pre.prf \
		../../../raspi/qt5/mkspecs/common/unix.conf \
		../../../raspi/qt5/mkspecs/common/linux.conf \
		../../../raspi/qt5/mkspecs/common/sanitize.conf \
		../../../raspi/qt5/mkspecs/common/gcc-base.conf \
		../../../raspi/qt5/mkspecs/common/gcc-base-unix.conf \
		../../../raspi/qt5/mkspecs/common/g++-base.conf \
		../../../raspi/qt5/mkspecs/common/g++-unix.conf \
		../../../raspi/qt5/mkspecs/qdevice.pri \
		../../../raspi/qt5/mkspecs/features/device_config.prf \
		../../../raspi/qt5/mkspecs/devices/common/linux_device_pre.conf \
		../../../raspi/qt5/mkspecs/devices/common/linux_device_post.conf \
		../../../raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf \
		../../../raspi/qt5/mkspecs/qconfig.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3drender.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_charts.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_core.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_gui.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_help.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_help_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_network.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_nfc.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_purchasing.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_qml.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_quick.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_repparser.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_scxml.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_sensors.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_serialport.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_sql.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_svg.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_uitools.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_websockets.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_webview.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_webview_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_xml.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		../../../raspi/qt5/mkspecs/features/qt_functions.prf \
		../../../raspi/qt5/mkspecs/features/qt_config.prf \
		../../../raspi/qt5/mkspecs/devices/linux-rasp-pi-g++/qmake.conf \
		../../../raspi/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../raspi/qt5/mkspecs/features/exclusive_builds.prf \
		../../../raspi/qt5/mkspecs/features/toolchain.prf \
		../../../raspi/qt5/mkspecs/features/default_pre.prf \
		../../../raspi/qt5/mkspecs/features/resolve_config.prf \
		../../../raspi/qt5/mkspecs/features/default_post.prf \
		../../../raspi/qt5/mkspecs/features/resources.prf \
		../../../raspi/qt5/mkspecs/features/qtquickcompiler.prf \
		../../../raspi/qt5/mkspecs/features/warn_on.prf \
		../../../raspi/qt5/mkspecs/features/qt.prf \
		../../../raspi/qt5/mkspecs/features/moc.prf \
		../../../raspi/qt5/mkspecs/features/unix/opengl.prf \
		../../../raspi/qt5/mkspecs/features/uic.prf \
		../../../raspi/qt5/mkspecs/features/unix/thread.prf \
		../../../raspi/qt5/mkspecs/features/qmake_use.prf \
		../../../raspi/qt5/mkspecs/features/file_copies.prf \
		../../../raspi/qt5/mkspecs/features/testcase_targets.prf \
		../../../raspi/qt5/mkspecs/features/exceptions.prf \
		../../../raspi/qt5/mkspecs/features/yacc.prf \
		../../../raspi/qt5/mkspecs/features/lex.prf \
		mycar.pro DriveModule.h \
		SensorsModule.h \
		mainwindow.h DriveModule.cpp \
		SensorsModule.cpp \
		main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = mycar
DESTDIR       = 
TARGET        = mycar


first: all
####### Build rules

mycar: ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mycar.pro ../../../raspi/qt5/mkspecs/devices/linux-rasp-pi-g++/qmake.conf ../../../raspi/qt5/mkspecs/features/spec_pre.prf \
		../../../raspi/qt5/mkspecs/common/unix.conf \
		../../../raspi/qt5/mkspecs/common/linux.conf \
		../../../raspi/qt5/mkspecs/common/sanitize.conf \
		../../../raspi/qt5/mkspecs/common/gcc-base.conf \
		../../../raspi/qt5/mkspecs/common/gcc-base-unix.conf \
		../../../raspi/qt5/mkspecs/common/g++-base.conf \
		../../../raspi/qt5/mkspecs/common/g++-unix.conf \
		../../../raspi/qt5/mkspecs/qdevice.pri \
		../../../raspi/qt5/mkspecs/features/device_config.prf \
		../../../raspi/qt5/mkspecs/devices/common/linux_device_pre.conf \
		../../../raspi/qt5/mkspecs/devices/common/linux_device_post.conf \
		../../../raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf \
		../../../raspi/qt5/mkspecs/qconfig.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3drender.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_charts.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_core.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_gui.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_help.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_help_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_network.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_nfc.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_purchasing.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_qml.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_quick.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_repparser.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_scxml.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_sensors.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_serialport.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_sql.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_svg.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_uitools.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_websockets.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_webview.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_webview_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_xml.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		../../../raspi/qt5/mkspecs/features/qt_functions.prf \
		../../../raspi/qt5/mkspecs/features/qt_config.prf \
		../../../raspi/qt5/mkspecs/devices/linux-rasp-pi-g++/qmake.conf \
		../../../raspi/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../raspi/qt5/mkspecs/features/exclusive_builds.prf \
		../../../raspi/qt5/mkspecs/features/toolchain.prf \
		../../../raspi/qt5/mkspecs/features/default_pre.prf \
		../../../raspi/qt5/mkspecs/features/resolve_config.prf \
		../../../raspi/qt5/mkspecs/features/default_post.prf \
		../../../raspi/qt5/mkspecs/features/resources.prf \
		../../../raspi/qt5/mkspecs/features/qtquickcompiler.prf \
		../../../raspi/qt5/mkspecs/features/warn_on.prf \
		../../../raspi/qt5/mkspecs/features/qt.prf \
		../../../raspi/qt5/mkspecs/features/moc.prf \
		../../../raspi/qt5/mkspecs/features/unix/opengl.prf \
		../../../raspi/qt5/mkspecs/features/uic.prf \
		../../../raspi/qt5/mkspecs/features/unix/thread.prf \
		../../../raspi/qt5/mkspecs/features/qmake_use.prf \
		../../../raspi/qt5/mkspecs/features/file_copies.prf \
		../../../raspi/qt5/mkspecs/features/testcase_targets.prf \
		../../../raspi/qt5/mkspecs/features/exceptions.prf \
		../../../raspi/qt5/mkspecs/features/yacc.prf \
		../../../raspi/qt5/mkspecs/features/lex.prf \
		mycar.pro
	$(QMAKE) -o Makefile mycar.pro -spec devices/linux-rasp-pi-g++ CONFIG+=qtquickcompiler
../../../raspi/qt5/mkspecs/features/spec_pre.prf:
../../../raspi/qt5/mkspecs/common/unix.conf:
../../../raspi/qt5/mkspecs/common/linux.conf:
../../../raspi/qt5/mkspecs/common/sanitize.conf:
../../../raspi/qt5/mkspecs/common/gcc-base.conf:
../../../raspi/qt5/mkspecs/common/gcc-base-unix.conf:
../../../raspi/qt5/mkspecs/common/g++-base.conf:
../../../raspi/qt5/mkspecs/common/g++-unix.conf:
../../../raspi/qt5/mkspecs/qdevice.pri:
../../../raspi/qt5/mkspecs/features/device_config.prf:
../../../raspi/qt5/mkspecs/devices/common/linux_device_pre.conf:
../../../raspi/qt5/mkspecs/devices/common/linux_device_post.conf:
../../../raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf:
../../../raspi/qt5/mkspecs/qconfig.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3danimation.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3dcore.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3dextras.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3dinput.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3dquick.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3drender.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_charts.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_charts_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_core.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_core_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_datavisualization.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_dbus.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_gamepad.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_gui.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_help.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_help_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_multimedia.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_network.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_network_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_networkauth.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_nfc.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_opengl.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_purchasing.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_qml.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_qml_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_qmltest.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_quick.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_quick_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_repparser.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_repparser_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_scxml.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_scxml_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_sensors.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_serialbus.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_serialport.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_sql.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_svg.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_svg_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_testlib.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_texttospeech.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_uitools.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_webchannel.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_websockets.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_webview.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_webview_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_widgets.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_x11extras.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_xml.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
../../../raspi/qt5/mkspecs/features/qt_functions.prf:
../../../raspi/qt5/mkspecs/features/qt_config.prf:
../../../raspi/qt5/mkspecs/devices/linux-rasp-pi-g++/qmake.conf:
../../../raspi/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../raspi/qt5/mkspecs/features/exclusive_builds.prf:
../../../raspi/qt5/mkspecs/features/toolchain.prf:
../../../raspi/qt5/mkspecs/features/default_pre.prf:
../../../raspi/qt5/mkspecs/features/resolve_config.prf:
../../../raspi/qt5/mkspecs/features/default_post.prf:
../../../raspi/qt5/mkspecs/features/resources.prf:
../../../raspi/qt5/mkspecs/features/qtquickcompiler.prf:
../../../raspi/qt5/mkspecs/features/warn_on.prf:
../../../raspi/qt5/mkspecs/features/qt.prf:
../../../raspi/qt5/mkspecs/features/moc.prf:
../../../raspi/qt5/mkspecs/features/unix/opengl.prf:
../../../raspi/qt5/mkspecs/features/uic.prf:
../../../raspi/qt5/mkspecs/features/unix/thread.prf:
../../../raspi/qt5/mkspecs/features/qmake_use.prf:
../../../raspi/qt5/mkspecs/features/file_copies.prf:
../../../raspi/qt5/mkspecs/features/testcase_targets.prf:
../../../raspi/qt5/mkspecs/features/exceptions.prf:
../../../raspi/qt5/mkspecs/features/yacc.prf:
../../../raspi/qt5/mkspecs/features/lex.prf:
mycar.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile mycar.pro -spec devices/linux-rasp-pi-g++ CONFIG+=qtquickcompiler

qmake_all: FORCE


all: Makefile mycar

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../raspi/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents DriveModule.h SensorsModule.h mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents DriveModule.cpp SensorsModule.cpp main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_qmlcache_make_all:
compiler_qmlcache_clean:
compiler_qmlcache_loader_make_all: qmlcache_loader.cpp
compiler_qmlcache_loader_clean:
	-$(DEL_FILE) qmlcache_loader.cpp
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../raspi/qt5/mkspecs/features/data/dummy.cpp
	/home/mateusz/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++ -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s -march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard --sysroot=/home/mateusz/raspi/sysroot -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../../raspi/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h \
		../../../raspi/qt5pi/include/QtWidgets/QMainWindow \
		../../../raspi/qt5pi/include/QtWidgets/qmainwindow.h \
		../../../raspi/qt5pi/include/QtWidgets/qtwidgetsglobal.h \
		../../../raspi/qt5pi/include/QtGui/qtguiglobal.h \
		../../../raspi/qt5pi/include/QtCore/qglobal.h \
		../../../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../../../raspi/qt5pi/include/QtCore/qconfig.h \
		../../../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../../../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../../../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../../../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../../../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../../../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../../../raspi/qt5pi/include/QtCore/qlogging.h \
		../../../raspi/qt5pi/include/QtCore/qflags.h \
		../../../raspi/qt5pi/include/QtCore/qatomic.h \
		../../../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../../../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../../../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../../../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../../../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../../../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../../../raspi/qt5pi/include/QtCore/qmutex.h \
		../../../raspi/qt5pi/include/QtCore/qnumeric.h \
		../../../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../../../raspi/qt5pi/include/QtGui/qtgui-config.h \
		../../../raspi/qt5pi/include/QtWidgets/qtwidgets-config.h \
		../../../raspi/qt5pi/include/QtWidgets/qwidget.h \
		../../../raspi/qt5pi/include/QtGui/qwindowdefs.h \
		../../../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../../../raspi/qt5pi/include/QtCore/qnamespace.h \
		../../../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../../../raspi/qt5pi/include/QtGui/qwindowdefs_win.h \
		../../../raspi/qt5pi/include/QtCore/qobject.h \
		../../../raspi/qt5pi/include/QtCore/qstring.h \
		../../../raspi/qt5pi/include/QtCore/qchar.h \
		../../../raspi/qt5pi/include/QtCore/qbytearray.h \
		../../../raspi/qt5pi/include/QtCore/qrefcount.h \
		../../../raspi/qt5pi/include/QtCore/qarraydata.h \
		../../../raspi/qt5pi/include/QtCore/qstringliteral.h \
		../../../raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		../../../raspi/qt5pi/include/QtCore/qstringview.h \
		../../../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../../../raspi/qt5pi/include/QtCore/qlist.h \
		../../../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../../../raspi/qt5pi/include/QtCore/qiterator.h \
		../../../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../../../raspi/qt5pi/include/QtCore/qpair.h \
		../../../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../../../raspi/qt5pi/include/QtCore/qstringlist.h \
		../../../raspi/qt5pi/include/QtCore/qregexp.h \
		../../../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../../../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../../../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../../../raspi/qt5pi/include/QtCore/qmetatype.h \
		../../../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../../../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../../../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../../../raspi/qt5pi/include/QtCore/qmargins.h \
		../../../raspi/qt5pi/include/QtGui/qpaintdevice.h \
		../../../raspi/qt5pi/include/QtCore/qrect.h \
		../../../raspi/qt5pi/include/QtCore/qsize.h \
		../../../raspi/qt5pi/include/QtCore/qpoint.h \
		../../../raspi/qt5pi/include/QtGui/qpalette.h \
		../../../raspi/qt5pi/include/QtGui/qcolor.h \
		../../../raspi/qt5pi/include/QtGui/qrgb.h \
		../../../raspi/qt5pi/include/QtGui/qrgba64.h \
		../../../raspi/qt5pi/include/QtGui/qbrush.h \
		../../../raspi/qt5pi/include/QtCore/qvector.h \
		../../../raspi/qt5pi/include/QtGui/qmatrix.h \
		../../../raspi/qt5pi/include/QtGui/qpolygon.h \
		../../../raspi/qt5pi/include/QtGui/qregion.h \
		../../../raspi/qt5pi/include/QtCore/qdatastream.h \
		../../../raspi/qt5pi/include/QtCore/qiodevice.h \
		../../../raspi/qt5pi/include/QtCore/qline.h \
		../../../raspi/qt5pi/include/QtGui/qtransform.h \
		../../../raspi/qt5pi/include/QtGui/qpainterpath.h \
		../../../raspi/qt5pi/include/QtGui/qimage.h \
		../../../raspi/qt5pi/include/QtGui/qpixelformat.h \
		../../../raspi/qt5pi/include/QtGui/qpixmap.h \
		../../../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../../../raspi/qt5pi/include/QtCore/qshareddata.h \
		../../../raspi/qt5pi/include/QtCore/qhash.h \
		../../../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../../../raspi/qt5pi/include/QtGui/qfont.h \
		../../../raspi/qt5pi/include/QtGui/qfontmetrics.h \
		../../../raspi/qt5pi/include/QtGui/qfontinfo.h \
		../../../raspi/qt5pi/include/QtWidgets/qsizepolicy.h \
		../../../raspi/qt5pi/include/QtGui/qcursor.h \
		../../../raspi/qt5pi/include/QtGui/qkeysequence.h \
		../../../raspi/qt5pi/include/QtGui/qevent.h \
		../../../raspi/qt5pi/include/QtCore/qvariant.h \
		../../../raspi/qt5pi/include/QtCore/qmap.h \
		../../../raspi/qt5pi/include/QtCore/qdebug.h \
		../../../raspi/qt5pi/include/QtCore/qtextstream.h \
		../../../raspi/qt5pi/include/QtCore/qlocale.h \
		../../../raspi/qt5pi/include/QtCore/qset.h \
		../../../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../../../raspi/qt5pi/include/QtCore/qurl.h \
		../../../raspi/qt5pi/include/QtCore/qurlquery.h \
		../../../raspi/qt5pi/include/QtCore/qfile.h \
		../../../raspi/qt5pi/include/QtCore/qfiledevice.h \
		../../../raspi/qt5pi/include/QtGui/qvector2d.h \
		../../../raspi/qt5pi/include/QtGui/qtouchdevice.h \
		../../../raspi/qt5pi/include/QtWidgets/qtabwidget.h \
		../../../raspi/qt5pi/include/QtGui/qicon.h \
		../../../raspi/qt5pi/include/QtCore/QString \
		../../../raspi/qt5pi/include/QtCore/QObject \
		DriveModule.h \
		../../../raspi/qt5pi/include/QtCore/QDateTime \
		../../../raspi/qt5pi/include/QtCore/qdatetime.h \
		../../../raspi/qt5pi/include/QtCore/QTimer \
		../../../raspi/qt5pi/include/QtCore/qtimer.h \
		../../../raspi/qt5pi/include/QtCore/qbasictimer.h \
		SensorsModule.h \
		moc_predefs.h \
		../../../raspi/qt5/bin/moc
	/home/mateusz/raspi/qt5/bin/moc $(DEFINES) --include /home/mateusz/Desktop/QtPojects/mycar/moc_predefs.h -I/home/mateusz/raspi/qt5/mkspecs/devices/linux-rasp-pi-g++ -I/home/mateusz/Desktop/QtPojects/mycar -I/raspi/sysroot/usr/include -I/home/mateusz/raspi/qt5pi/include -I/home/mateusz/raspi/qt5pi/include/QtWidgets -I/home/mateusz/raspi/qt5pi/include/QtGui -I/home/mateusz/raspi/qt5pi/include/QtCore -I/home/mateusz/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3 -I/home/mateusz/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/arm-linux-gnueabihf -I/home/mateusz/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/backward -I/home/mateusz/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include -I/home/mateusz/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include-fixed -I/home/mateusz/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include -I/home/mateusz/raspi/sysroot/usr/include -I/home/mateusz/raspi/sysroot/usr/include/arm-linux-gnueabihf mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../../../raspi/qt5/bin/uic
	/home/mateusz/raspi/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

DriveModule.o: DriveModule.cpp DriveModule.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DriveModule.o DriveModule.cpp

SensorsModule.o: SensorsModule.cpp SensorsModule.h \
		../../../raspi/qt5pi/include/QtWidgets/QMainWindow \
		../../../raspi/qt5pi/include/QtWidgets/qmainwindow.h \
		../../../raspi/qt5pi/include/QtWidgets/qtwidgetsglobal.h \
		../../../raspi/qt5pi/include/QtGui/qtguiglobal.h \
		../../../raspi/qt5pi/include/QtCore/qglobal.h \
		../../../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../../../raspi/qt5pi/include/QtCore/qconfig.h \
		../../../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../../../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../../../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../../../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../../../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../../../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../../../raspi/qt5pi/include/QtCore/qlogging.h \
		../../../raspi/qt5pi/include/QtCore/qflags.h \
		../../../raspi/qt5pi/include/QtCore/qatomic.h \
		../../../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../../../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../../../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../../../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../../../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../../../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../../../raspi/qt5pi/include/QtCore/qmutex.h \
		../../../raspi/qt5pi/include/QtCore/qnumeric.h \
		../../../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../../../raspi/qt5pi/include/QtGui/qtgui-config.h \
		../../../raspi/qt5pi/include/QtWidgets/qtwidgets-config.h \
		../../../raspi/qt5pi/include/QtWidgets/qwidget.h \
		../../../raspi/qt5pi/include/QtGui/qwindowdefs.h \
		../../../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../../../raspi/qt5pi/include/QtCore/qnamespace.h \
		../../../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../../../raspi/qt5pi/include/QtGui/qwindowdefs_win.h \
		../../../raspi/qt5pi/include/QtCore/qobject.h \
		../../../raspi/qt5pi/include/QtCore/qstring.h \
		../../../raspi/qt5pi/include/QtCore/qchar.h \
		../../../raspi/qt5pi/include/QtCore/qbytearray.h \
		../../../raspi/qt5pi/include/QtCore/qrefcount.h \
		../../../raspi/qt5pi/include/QtCore/qarraydata.h \
		../../../raspi/qt5pi/include/QtCore/qstringliteral.h \
		../../../raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		../../../raspi/qt5pi/include/QtCore/qstringview.h \
		../../../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../../../raspi/qt5pi/include/QtCore/qlist.h \
		../../../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../../../raspi/qt5pi/include/QtCore/qiterator.h \
		../../../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../../../raspi/qt5pi/include/QtCore/qpair.h \
		../../../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../../../raspi/qt5pi/include/QtCore/qstringlist.h \
		../../../raspi/qt5pi/include/QtCore/qregexp.h \
		../../../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../../../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../../../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../../../raspi/qt5pi/include/QtCore/qmetatype.h \
		../../../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../../../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../../../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../../../raspi/qt5pi/include/QtCore/qmargins.h \
		../../../raspi/qt5pi/include/QtGui/qpaintdevice.h \
		../../../raspi/qt5pi/include/QtCore/qrect.h \
		../../../raspi/qt5pi/include/QtCore/qsize.h \
		../../../raspi/qt5pi/include/QtCore/qpoint.h \
		../../../raspi/qt5pi/include/QtGui/qpalette.h \
		../../../raspi/qt5pi/include/QtGui/qcolor.h \
		../../../raspi/qt5pi/include/QtGui/qrgb.h \
		../../../raspi/qt5pi/include/QtGui/qrgba64.h \
		../../../raspi/qt5pi/include/QtGui/qbrush.h \
		../../../raspi/qt5pi/include/QtCore/qvector.h \
		../../../raspi/qt5pi/include/QtGui/qmatrix.h \
		../../../raspi/qt5pi/include/QtGui/qpolygon.h \
		../../../raspi/qt5pi/include/QtGui/qregion.h \
		../../../raspi/qt5pi/include/QtCore/qdatastream.h \
		../../../raspi/qt5pi/include/QtCore/qiodevice.h \
		../../../raspi/qt5pi/include/QtCore/qline.h \
		../../../raspi/qt5pi/include/QtGui/qtransform.h \
		../../../raspi/qt5pi/include/QtGui/qpainterpath.h \
		../../../raspi/qt5pi/include/QtGui/qimage.h \
		../../../raspi/qt5pi/include/QtGui/qpixelformat.h \
		../../../raspi/qt5pi/include/QtGui/qpixmap.h \
		../../../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../../../raspi/qt5pi/include/QtCore/qshareddata.h \
		../../../raspi/qt5pi/include/QtCore/qhash.h \
		../../../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../../../raspi/qt5pi/include/QtGui/qfont.h \
		../../../raspi/qt5pi/include/QtGui/qfontmetrics.h \
		../../../raspi/qt5pi/include/QtGui/qfontinfo.h \
		../../../raspi/qt5pi/include/QtWidgets/qsizepolicy.h \
		../../../raspi/qt5pi/include/QtGui/qcursor.h \
		../../../raspi/qt5pi/include/QtGui/qkeysequence.h \
		../../../raspi/qt5pi/include/QtGui/qevent.h \
		../../../raspi/qt5pi/include/QtCore/qvariant.h \
		../../../raspi/qt5pi/include/QtCore/qmap.h \
		../../../raspi/qt5pi/include/QtCore/qdebug.h \
		../../../raspi/qt5pi/include/QtCore/qtextstream.h \
		../../../raspi/qt5pi/include/QtCore/qlocale.h \
		../../../raspi/qt5pi/include/QtCore/qset.h \
		../../../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../../../raspi/qt5pi/include/QtCore/qurl.h \
		../../../raspi/qt5pi/include/QtCore/qurlquery.h \
		../../../raspi/qt5pi/include/QtCore/qfile.h \
		../../../raspi/qt5pi/include/QtCore/qfiledevice.h \
		../../../raspi/qt5pi/include/QtGui/qvector2d.h \
		../../../raspi/qt5pi/include/QtGui/qtouchdevice.h \
		../../../raspi/qt5pi/include/QtWidgets/qtabwidget.h \
		../../../raspi/qt5pi/include/QtGui/qicon.h \
		../../../raspi/qt5pi/include/QtCore/QString \
		../../../raspi/qt5pi/include/QtCore/QObject \
		DriveModule.h \
		../../../raspi/qt5pi/include/QtCore/QDateTime \
		../../../raspi/qt5pi/include/QtCore/qdatetime.h \
		../../../raspi/qt5pi/include/QtCore/QTimer \
		../../../raspi/qt5pi/include/QtCore/qtimer.h \
		../../../raspi/qt5pi/include/QtCore/qbasictimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SensorsModule.o SensorsModule.cpp

main.o: main.cpp mainwindow.h \
		../../../raspi/qt5pi/include/QtWidgets/QMainWindow \
		../../../raspi/qt5pi/include/QtWidgets/qmainwindow.h \
		../../../raspi/qt5pi/include/QtWidgets/qtwidgetsglobal.h \
		../../../raspi/qt5pi/include/QtGui/qtguiglobal.h \
		../../../raspi/qt5pi/include/QtCore/qglobal.h \
		../../../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../../../raspi/qt5pi/include/QtCore/qconfig.h \
		../../../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../../../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../../../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../../../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../../../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../../../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../../../raspi/qt5pi/include/QtCore/qlogging.h \
		../../../raspi/qt5pi/include/QtCore/qflags.h \
		../../../raspi/qt5pi/include/QtCore/qatomic.h \
		../../../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../../../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../../../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../../../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../../../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../../../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../../../raspi/qt5pi/include/QtCore/qmutex.h \
		../../../raspi/qt5pi/include/QtCore/qnumeric.h \
		../../../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../../../raspi/qt5pi/include/QtGui/qtgui-config.h \
		../../../raspi/qt5pi/include/QtWidgets/qtwidgets-config.h \
		../../../raspi/qt5pi/include/QtWidgets/qwidget.h \
		../../../raspi/qt5pi/include/QtGui/qwindowdefs.h \
		../../../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../../../raspi/qt5pi/include/QtCore/qnamespace.h \
		../../../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../../../raspi/qt5pi/include/QtGui/qwindowdefs_win.h \
		../../../raspi/qt5pi/include/QtCore/qobject.h \
		../../../raspi/qt5pi/include/QtCore/qstring.h \
		../../../raspi/qt5pi/include/QtCore/qchar.h \
		../../../raspi/qt5pi/include/QtCore/qbytearray.h \
		../../../raspi/qt5pi/include/QtCore/qrefcount.h \
		../../../raspi/qt5pi/include/QtCore/qarraydata.h \
		../../../raspi/qt5pi/include/QtCore/qstringliteral.h \
		../../../raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		../../../raspi/qt5pi/include/QtCore/qstringview.h \
		../../../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../../../raspi/qt5pi/include/QtCore/qlist.h \
		../../../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../../../raspi/qt5pi/include/QtCore/qiterator.h \
		../../../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../../../raspi/qt5pi/include/QtCore/qpair.h \
		../../../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../../../raspi/qt5pi/include/QtCore/qstringlist.h \
		../../../raspi/qt5pi/include/QtCore/qregexp.h \
		../../../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../../../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../../../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../../../raspi/qt5pi/include/QtCore/qmetatype.h \
		../../../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../../../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../../../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../../../raspi/qt5pi/include/QtCore/qmargins.h \
		../../../raspi/qt5pi/include/QtGui/qpaintdevice.h \
		../../../raspi/qt5pi/include/QtCore/qrect.h \
		../../../raspi/qt5pi/include/QtCore/qsize.h \
		../../../raspi/qt5pi/include/QtCore/qpoint.h \
		../../../raspi/qt5pi/include/QtGui/qpalette.h \
		../../../raspi/qt5pi/include/QtGui/qcolor.h \
		../../../raspi/qt5pi/include/QtGui/qrgb.h \
		../../../raspi/qt5pi/include/QtGui/qrgba64.h \
		../../../raspi/qt5pi/include/QtGui/qbrush.h \
		../../../raspi/qt5pi/include/QtCore/qvector.h \
		../../../raspi/qt5pi/include/QtGui/qmatrix.h \
		../../../raspi/qt5pi/include/QtGui/qpolygon.h \
		../../../raspi/qt5pi/include/QtGui/qregion.h \
		../../../raspi/qt5pi/include/QtCore/qdatastream.h \
		../../../raspi/qt5pi/include/QtCore/qiodevice.h \
		../../../raspi/qt5pi/include/QtCore/qline.h \
		../../../raspi/qt5pi/include/QtGui/qtransform.h \
		../../../raspi/qt5pi/include/QtGui/qpainterpath.h \
		../../../raspi/qt5pi/include/QtGui/qimage.h \
		../../../raspi/qt5pi/include/QtGui/qpixelformat.h \
		../../../raspi/qt5pi/include/QtGui/qpixmap.h \
		../../../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../../../raspi/qt5pi/include/QtCore/qshareddata.h \
		../../../raspi/qt5pi/include/QtCore/qhash.h \
		../../../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../../../raspi/qt5pi/include/QtGui/qfont.h \
		../../../raspi/qt5pi/include/QtGui/qfontmetrics.h \
		../../../raspi/qt5pi/include/QtGui/qfontinfo.h \
		../../../raspi/qt5pi/include/QtWidgets/qsizepolicy.h \
		../../../raspi/qt5pi/include/QtGui/qcursor.h \
		../../../raspi/qt5pi/include/QtGui/qkeysequence.h \
		../../../raspi/qt5pi/include/QtGui/qevent.h \
		../../../raspi/qt5pi/include/QtCore/qvariant.h \
		../../../raspi/qt5pi/include/QtCore/qmap.h \
		../../../raspi/qt5pi/include/QtCore/qdebug.h \
		../../../raspi/qt5pi/include/QtCore/qtextstream.h \
		../../../raspi/qt5pi/include/QtCore/qlocale.h \
		../../../raspi/qt5pi/include/QtCore/qset.h \
		../../../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../../../raspi/qt5pi/include/QtCore/qurl.h \
		../../../raspi/qt5pi/include/QtCore/qurlquery.h \
		../../../raspi/qt5pi/include/QtCore/qfile.h \
		../../../raspi/qt5pi/include/QtCore/qfiledevice.h \
		../../../raspi/qt5pi/include/QtGui/qvector2d.h \
		../../../raspi/qt5pi/include/QtGui/qtouchdevice.h \
		../../../raspi/qt5pi/include/QtWidgets/qtabwidget.h \
		../../../raspi/qt5pi/include/QtGui/qicon.h \
		../../../raspi/qt5pi/include/QtCore/QString \
		../../../raspi/qt5pi/include/QtCore/QObject \
		DriveModule.h \
		../../../raspi/qt5pi/include/QtCore/QDateTime \
		../../../raspi/qt5pi/include/QtCore/qdatetime.h \
		../../../raspi/qt5pi/include/QtCore/QTimer \
		../../../raspi/qt5pi/include/QtCore/qtimer.h \
		../../../raspi/qt5pi/include/QtCore/qbasictimer.h \
		SensorsModule.h \
		../../../raspi/qt5pi/include/QtWidgets/QApplication \
		../../../raspi/qt5pi/include/QtWidgets/qapplication.h \
		../../../raspi/qt5pi/include/QtCore/qcoreapplication.h \
		../../../raspi/qt5pi/include/QtCore/qeventloop.h \
		../../../raspi/qt5pi/include/QtWidgets/qdesktopwidget.h \
		../../../raspi/qt5pi/include/QtGui/qguiapplication.h \
		../../../raspi/qt5pi/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../raspi/qt5pi/include/QtWidgets/QMainWindow \
		../../../raspi/qt5pi/include/QtWidgets/qmainwindow.h \
		../../../raspi/qt5pi/include/QtWidgets/qtwidgetsglobal.h \
		../../../raspi/qt5pi/include/QtGui/qtguiglobal.h \
		../../../raspi/qt5pi/include/QtCore/qglobal.h \
		../../../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../../../raspi/qt5pi/include/QtCore/qconfig.h \
		../../../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../../../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../../../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../../../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../../../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../../../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../../../raspi/qt5pi/include/QtCore/qlogging.h \
		../../../raspi/qt5pi/include/QtCore/qflags.h \
		../../../raspi/qt5pi/include/QtCore/qatomic.h \
		../../../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../../../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../../../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../../../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../../../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../../../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../../../raspi/qt5pi/include/QtCore/qmutex.h \
		../../../raspi/qt5pi/include/QtCore/qnumeric.h \
		../../../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../../../raspi/qt5pi/include/QtGui/qtgui-config.h \
		../../../raspi/qt5pi/include/QtWidgets/qtwidgets-config.h \
		../../../raspi/qt5pi/include/QtWidgets/qwidget.h \
		../../../raspi/qt5pi/include/QtGui/qwindowdefs.h \
		../../../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../../../raspi/qt5pi/include/QtCore/qnamespace.h \
		../../../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../../../raspi/qt5pi/include/QtGui/qwindowdefs_win.h \
		../../../raspi/qt5pi/include/QtCore/qobject.h \
		../../../raspi/qt5pi/include/QtCore/qstring.h \
		../../../raspi/qt5pi/include/QtCore/qchar.h \
		../../../raspi/qt5pi/include/QtCore/qbytearray.h \
		../../../raspi/qt5pi/include/QtCore/qrefcount.h \
		../../../raspi/qt5pi/include/QtCore/qarraydata.h \
		../../../raspi/qt5pi/include/QtCore/qstringliteral.h \
		../../../raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		../../../raspi/qt5pi/include/QtCore/qstringview.h \
		../../../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../../../raspi/qt5pi/include/QtCore/qlist.h \
		../../../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../../../raspi/qt5pi/include/QtCore/qiterator.h \
		../../../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../../../raspi/qt5pi/include/QtCore/qpair.h \
		../../../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../../../raspi/qt5pi/include/QtCore/qstringlist.h \
		../../../raspi/qt5pi/include/QtCore/qregexp.h \
		../../../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../../../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../../../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../../../raspi/qt5pi/include/QtCore/qmetatype.h \
		../../../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../../../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../../../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../../../raspi/qt5pi/include/QtCore/qmargins.h \
		../../../raspi/qt5pi/include/QtGui/qpaintdevice.h \
		../../../raspi/qt5pi/include/QtCore/qrect.h \
		../../../raspi/qt5pi/include/QtCore/qsize.h \
		../../../raspi/qt5pi/include/QtCore/qpoint.h \
		../../../raspi/qt5pi/include/QtGui/qpalette.h \
		../../../raspi/qt5pi/include/QtGui/qcolor.h \
		../../../raspi/qt5pi/include/QtGui/qrgb.h \
		../../../raspi/qt5pi/include/QtGui/qrgba64.h \
		../../../raspi/qt5pi/include/QtGui/qbrush.h \
		../../../raspi/qt5pi/include/QtCore/qvector.h \
		../../../raspi/qt5pi/include/QtGui/qmatrix.h \
		../../../raspi/qt5pi/include/QtGui/qpolygon.h \
		../../../raspi/qt5pi/include/QtGui/qregion.h \
		../../../raspi/qt5pi/include/QtCore/qdatastream.h \
		../../../raspi/qt5pi/include/QtCore/qiodevice.h \
		../../../raspi/qt5pi/include/QtCore/qline.h \
		../../../raspi/qt5pi/include/QtGui/qtransform.h \
		../../../raspi/qt5pi/include/QtGui/qpainterpath.h \
		../../../raspi/qt5pi/include/QtGui/qimage.h \
		../../../raspi/qt5pi/include/QtGui/qpixelformat.h \
		../../../raspi/qt5pi/include/QtGui/qpixmap.h \
		../../../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../../../raspi/qt5pi/include/QtCore/qshareddata.h \
		../../../raspi/qt5pi/include/QtCore/qhash.h \
		../../../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../../../raspi/qt5pi/include/QtGui/qfont.h \
		../../../raspi/qt5pi/include/QtGui/qfontmetrics.h \
		../../../raspi/qt5pi/include/QtGui/qfontinfo.h \
		../../../raspi/qt5pi/include/QtWidgets/qsizepolicy.h \
		../../../raspi/qt5pi/include/QtGui/qcursor.h \
		../../../raspi/qt5pi/include/QtGui/qkeysequence.h \
		../../../raspi/qt5pi/include/QtGui/qevent.h \
		../../../raspi/qt5pi/include/QtCore/qvariant.h \
		../../../raspi/qt5pi/include/QtCore/qmap.h \
		../../../raspi/qt5pi/include/QtCore/qdebug.h \
		../../../raspi/qt5pi/include/QtCore/qtextstream.h \
		../../../raspi/qt5pi/include/QtCore/qlocale.h \
		../../../raspi/qt5pi/include/QtCore/qset.h \
		../../../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../../../raspi/qt5pi/include/QtCore/qurl.h \
		../../../raspi/qt5pi/include/QtCore/qurlquery.h \
		../../../raspi/qt5pi/include/QtCore/qfile.h \
		../../../raspi/qt5pi/include/QtCore/qfiledevice.h \
		../../../raspi/qt5pi/include/QtGui/qvector2d.h \
		../../../raspi/qt5pi/include/QtGui/qtouchdevice.h \
		../../../raspi/qt5pi/include/QtWidgets/qtabwidget.h \
		../../../raspi/qt5pi/include/QtGui/qicon.h \
		../../../raspi/qt5pi/include/QtCore/QString \
		../../../raspi/qt5pi/include/QtCore/QObject \
		DriveModule.h \
		../../../raspi/qt5pi/include/QtCore/QDateTime \
		../../../raspi/qt5pi/include/QtCore/qdatetime.h \
		../../../raspi/qt5pi/include/QtCore/QTimer \
		../../../raspi/qt5pi/include/QtCore/qtimer.h \
		../../../raspi/qt5pi/include/QtCore/qbasictimer.h \
		SensorsModule.h \
		ui_mainwindow.h \
		../../../raspi/qt5pi/include/QtCore/QVariant \
		../../../raspi/qt5pi/include/QtWidgets/QApplication \
		../../../raspi/qt5pi/include/QtWidgets/qapplication.h \
		../../../raspi/qt5pi/include/QtCore/qcoreapplication.h \
		../../../raspi/qt5pi/include/QtCore/qeventloop.h \
		../../../raspi/qt5pi/include/QtWidgets/qdesktopwidget.h \
		../../../raspi/qt5pi/include/QtGui/qguiapplication.h \
		../../../raspi/qt5pi/include/QtGui/qinputmethod.h \
		../../../raspi/qt5pi/include/QtWidgets/QGroupBox \
		../../../raspi/qt5pi/include/QtWidgets/qgroupbox.h \
		../../../raspi/qt5pi/include/QtWidgets/qframe.h \
		../../../raspi/qt5pi/include/QtWidgets/QLCDNumber \
		../../../raspi/qt5pi/include/QtWidgets/qlcdnumber.h \
		../../../raspi/qt5pi/include/QtWidgets/QLabel \
		../../../raspi/qt5pi/include/QtWidgets/qlabel.h \
		../../../raspi/qt5pi/include/QtWidgets/QMenuBar \
		../../../raspi/qt5pi/include/QtWidgets/qmenubar.h \
		../../../raspi/qt5pi/include/QtWidgets/qmenu.h \
		../../../raspi/qt5pi/include/QtWidgets/qaction.h \
		../../../raspi/qt5pi/include/QtWidgets/qactiongroup.h \
		../../../raspi/qt5pi/include/QtWidgets/QPushButton \
		../../../raspi/qt5pi/include/QtWidgets/qpushbutton.h \
		../../../raspi/qt5pi/include/QtWidgets/qabstractbutton.h \
		../../../raspi/qt5pi/include/QtWidgets/QRadioButton \
		../../../raspi/qt5pi/include/QtWidgets/qradiobutton.h \
		../../../raspi/qt5pi/include/QtWidgets/QSlider \
		../../../raspi/qt5pi/include/QtWidgets/qslider.h \
		../../../raspi/qt5pi/include/QtWidgets/qabstractslider.h \
		../../../raspi/qt5pi/include/QtWidgets/QStatusBar \
		../../../raspi/qt5pi/include/QtWidgets/qstatusbar.h \
		../../../raspi/qt5pi/include/QtWidgets/QTextEdit \
		../../../raspi/qt5pi/include/QtWidgets/qtextedit.h \
		../../../raspi/qt5pi/include/QtWidgets/qabstractscrollarea.h \
		../../../raspi/qt5pi/include/QtGui/qtextdocument.h \
		../../../raspi/qt5pi/include/QtGui/qtextoption.h \
		../../../raspi/qt5pi/include/QtGui/qtextcursor.h \
		../../../raspi/qt5pi/include/QtGui/qtextformat.h \
		../../../raspi/qt5pi/include/QtGui/qpen.h \
		../../../raspi/qt5pi/include/QtWidgets/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/home/pi/Desktop || mkdir -p $(INSTALL_ROOT)/home/pi/Desktop
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/home/pi/Desktop/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/home/pi/Desktop/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/home/pi/Desktop/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/home/pi/Desktop/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

